### ISSUE TITLE
Para o infinito e além

### ISSUE THREAD

**Issue by nazareno** [analytics-ufcg/enquadrados#10]
![image](https://cloud.githubusercontent.com/assets/1053850/18204383/e13c0bb8-70f2-11e6-95f5-2df65962b948.png)

**Comment by xibaca** [comment]
Eu acho que isso aconteceu durante um "deploy parcial": um frontend mais atualizado enquanto que o backend ainda estava em sua versão antiga (o deploy do front é via GitHub Pages enquanto que o backend está no Heroku, e cada deploy desse precisa ser feito manualmente de forma separada). De qualquer forma, @thiagoss disse que vai adicionar prevenções de divisões por zero throughout the code.

**Comment by xibaca** [comment]
Vou fechar essa issue por enquanto. Se o bug reemergir, essa issue será aberta novamente.
