### ISSUE TITLE
Adicionar google analytics

### ISSUE THREAD

**Issue by thiagoss** [analytics-ufcg/enquadrados#11]

**Comment by thiagoss** [comment]
@nazareno o analytics/hackfest tem algum super-container do analytics no google analytics? Ou cada projeto faz o seu independentemente?

**Comment by nazareno** [comment]
eu acho que temos, vou procurar e dou notícia

**Comment by thiagoss** [comment]
Eu criei um e botei, mas se tiver alguma outra que agrupe os projetos todos avisa que eu atualizo.
