### ISSUE TITLE
Responsividade nas 3 colunas de dados

### ISSUE THREAD

**Issue by nazareno** [analytics-ufcg/enquadrados#14]
Para as 3 colunas que parecem ser o principal, talvez só deixá-las dentro de uma `<div class="container-fluid">` já resolva, se vocês estiverem usando bootstrap. 

Não sei para o header, mas deve haver uma solução semelhante. Como está hoje: 

![image](https://cloud.githubusercontent.com/assets/1053850/18324601/bbf38384-7513-11e6-9c78-e37fc77b2677.png)

**Comment by nazareno** [comment]
quaase: 

<img width="395" alt="captura de tela 2016-09-08 as 20 49 31" src="https://cloud.githubusercontent.com/assets/1053850/18370748/e14af322-7605-11e6-9f01-3144909471a5.png">

o texto sai do espaço visível. 
e aproveitando: a caixa de busca também some no mobile.

**Comment by xibaca** [comment]
Eita, massa. Vou deixar a fonte menor ou com wrapping nesse caso.
