### ISSUE TITLE
A câmara de JP tem dois pavimentos

### ISSUE THREAD

**Issue by nazareno** [analytics-ufcg/enquadrados#18]
Não a parte do plenário, mas a dos escritórios e gabinetes tem primeiro andar. Talvez a área seja maior do que a que está computada no site hoje?

**Comment by xibaca** [comment]
Vou trazer meu irmão pra essa discussão porque ele vai poder confirmar, mas se não me engano me lembro que eles tiveram esse cuidado e de alguma forma, através do Google Earth e outro software de nome que não me recordo, eles incluíram a área de eventuais pavimentos adicionais também.

**Comment by Rafaelle** [comment]
Naza, eles tiveram o cuidado de verificar os pavimentos de todas as câmaras. Procuram o endereço pelo maps e depois confirmaram via earth e street view. 
A área foi calculada pelo daft logic e pelo earth, se tinha mais algum andar, colocávamos a base multiplicada pelo andar.

**Comment by nazareno** [comment]
ah, que bom então  :)
