### ISSUE TITLE
Link "estatísticas" na página inicial não leva a lugar algum

### ISSUE THREAD

**Issue by nazareno** [analytics-ufcg/enquadrados#9]
Ou não entendi o que ele é...

**Comment by xibaca** [comment]
Não, é verdade. Ele ainda não leva pra lugar algum, porque o seu destino é uma seção atualmente inexistente (issue #3) que informa com mais detalhes as estatísticas utilizadas pela gente, (acredito eu que) dando destaque à escala de metros quadrados por funcionário recomendadas pros diferentes tipos de estabelecimentos e talvez afirmando também como, caso alguma Câmara Municipal se encontre com uma certa razão, é físicamente impossível que todos os funcionários que constam na folha de pagamento (logo, devem trabalhar lá) trabalhem nesse mesmo ambiente ao mesmo tempo.

**Comment by xibaca** [comment]
Aí, a solução temporária vai ser esconder esse link até que #3 seja corrigido.
